### ISSUE TITLE
[Bug] Player be invincible and get infinite death effect after getting damage from projectile...

### ISSUE THREAD

**Issue by Ghostlyr** [TCPR/Thermos#172]
If a player wears on the head item with null protection from damage and get damage from projectile, throwed from other player, he gets null points of health, infinite death effect (shakes from side to side), can not pick up items, cant open any container, mobs do not attack him, and cannot death in no way. Even using kill command or kill and add health with plugin bug does not pass. Server rebooting too does not change anything. Same in creative gamemode. Other players can see that he is infinitely takes hurt with 0 health (from hunger).

**Steps to reproduce:**
1. Wear on the head only MOD item with ~0 armor protection (such as monocle from BiblioCraft or flower band from Biomes O Plenty) 
2. Ask friends for throw you any projectile with null damage (such as snowball or mudball from BiomesOPlenty) or throw youself with fishing rod.
3. Suffer from hangover

**Additional information:**
Not tested with vanilla forge.
Thermos build 32.
Has been noticed after update KC for 1614.193, but thermos with builded from 152...
Not tested without mods and plugins, but I do not think that they cause.
Unable to reproduce with glasses from Forestry and Railcraft, with them all be fine...
Tested on other server with other mods, common only are: Treecapitator 2.0.4, bspkrsCore 6.16, CodeChickenLib 1.1.3.140,  BiblioCraft 1.11.4, Chisel 1.5.7.
Major plugins: Essentials, ClearLag, WorldGuard, AutoSaveWorld, PermissionsEx, Vault, CombatLog, Scavenger, ProtocolLib, NoobProtector, HolographicDisplays, TagAPI.

I can transmit the broken player DAT file only to someone in person at the E-Mail adress. 
But there can be enough of this screenshot:
![1444141](https://cloud.githubusercontent.com/assets/8511068/13375137/1b04e53c-ddc2-11e5-929c-c71103637ef8.png)

Here screenshots of what is happening madness:
![654465456](https://cloud.githubusercontent.com/assets/8511068/13375216/3d2245c2-ddc4-11e5-868a-e671a11cba6b.png)
![465465](https://cloud.githubusercontent.com/assets/8511068/13375227/72f63d20-ddc4-11e5-9f2c-4628310df677.png)

**Comment by Bogdan-G** [comment]
`but thermos with builded from 152...` - This is not true at the moment, a thermos is based on a newer version of the KC, like 170+ build, with some corrections are not taken.

**Comment by Robotia** [comment]
Fixed in 36

**Comment by Ghostlyr** [comment]
Unfortunately, the problem is still happening

![screenshot](https://cloud.githubusercontent.com/assets/8511068/13485587/ad95b9b6-e133-11e5-8d97-791f501eb44e.png)
(i'm throw myself with fishing rod)

**Comment by Robotia** [comment]
Can you share video? Also, do items drop infinitely or is it just that effect?

**Comment by LemADEC** [comment]
What's the values of AbsorptionAmount and HealIF in your screenshot?
I'm able to reproduce this issue on my setup while wearing a Biome's o plenty Exotic flower band.
Notable mods compared to you:
Thermos-1.7.10-1614.35-bleeding-server.jar
Treecapitator 2.0.4 (same)
bspkrsCore 6.15 (you've 6.16)
CodeChickenLib 1.1.3.140 (same)
BiblioCraft 1.11.4 (same)
Chisel2-2.5.1.44 (you've Chisel 1.5.7 ?)
+ other mods

Regarding plugins, I don't have:
CombatLog, Scavenger, NoobProtector, HolographicDisplays, TagAPI.

**Comment by LemADEC** [comment]
I can reproduce with Thermos-1.7.10-1614.35-bleeding-server.jar and no plugins.
I can reproduce with Thermos-1.7.10-1614.37-bleeding-server.jar and no plugins.

**Comment by Ghostlyr** [comment]
> Can you share video?

![-1](https://cloud.githubusercontent.com/assets/8511068/13509943/702e9676-e1b8-11e5-806f-f7fd5c31b865.gif)

> Also, do items drop infinitely or is it just that effect?

Only effect.

**Comment by Robotia** [comment]
Hmm, what does the player look like to other people? Normal?

**Comment by LemADEC** [comment]
Players looks normal (vertical), you can see him jumping when it does try.

**Comment by Robotia** [comment]
@LemADEC @Ghostlyr see if B44 has fixed this?

**Comment by Ghostlyr** [comment]
Yes! It seems to this no longer occurs. Many thanks.

**Comment by Robotia** [comment]
Awesome!

**Comment by LemADEC** [comment]
Yes, it's fixed
