### ISSUE TITLE
[Bug] IC2 prod. machines

### ISSUE THREAD

**Issue by Isolonice** [TCPR/Thermos#192]
Hello,

With b33-34-UNOFF (maybe previous) players can't open production machines from IC2 like thermo, macerator, metal former etc, the skin isn't loading too

About versions: 
- industrialcraft-2-2.2.767-experimental.jar
- industrialcraft-2-2.2.804-experimental.jar
- industrialcraft-2-2.2.810-experimental.jar 
- industrialcraft-2-2.2.811-experimental.jar

**Comment by MixSt** [comment]
Confirm. 
industrialcraft-2-2.2.814-experimental

Also can not create IC2 "double crop".
No errors in logs.

**Comment by iKaneki-Ken** [comment]
Which build of Thermos are you using? As I can't reproduce this issue, which protection plugin are you using as well?

**Comment by Isolonice** [comment]
@iKaneki-Ken Without plugins on build : 33-34-UNOFF

Tried with Infinity Evolved v2.3.5
It doesn't work and on place it bug (side) : http://prnt.sc/aac1zj

**Comment by Robotia** [comment]
There are serious issues with 34 and 33, please do not use them for now. 31 should be fine.

35 planned release should fix this

**Comment by Isolonice** [comment]
@Robotia I can't start some servers with builds under b33 (always crashing on init, botania/thaumcraft..). Anyway i'll wait for b35, thanks :)

**Comment by Robotia** [comment]
Should be fixed in BL35

**Comment by Isolonice** [comment]
Same bug with b35

**Comment by linkinkov** [comment]
This was fixed?

**Comment by Isolonice** [comment]
Nope, do you have this problem too ?

**Comment by tyler2k15** [comment]
I can confirm this is still an Issue Running Thermos Build 39 on Infinity Evolved 2.3.5

http://prntscr.com/aazq82

Every IC2 block I place I am unable to interact with and many of them place with the front facing down oddly enough (unable to interact if I go under it as well)

**Comment by Robotia** [comment]
Fixed in B41

**Comment by floh22** [comment]
still getting this issue on B44 running Infinity Evolved 2.4.1

**Comment by Robotia** [comment]
Are you certain? I am not getting this issue, I tested it myself D:

**Comment by floh22** [comment]
nvm. someone changed the startup to use a specific Thermos version which was still in the folder for some reason. Organisation at its best ^^
