### ISSUE TITLE
[Crash]Crashing when joining a server with the build 40

### ISSUE THREAD

**Issue by mjra007** [TCPR/Thermos#202]
**Server Log:** 
No error whatsoever it just says "User mjra007 has disconnected, reason: Internal Exception: java.io.IOException: Connection reset by peer"

**Crash Report** 
https://paste.ubuntu.com/15287517/

**Explanation of issue:**
After updating Thermos to build 40 I crash every time I join the server, the server doesn't crash only the client. I used to use the build 32 and it worked fine.

**Thermos Version:**
Build 40 
**Forge Version:**
10.13.4.1614

**Comment by Robotia** [comment]
Your player data contains an invalid potion. Try resetting it.

**Comment by Robotia** [comment]
Fixed in B41.

**Comment by mjra007** [comment]
I tried with B44 and I am still getting the crash(https://paste.ubuntu.com/15305895/). I think the problem is caused by Ars Magica 2, because I can login just fine If I remove the mod(client-side and server-side).

**Comment by Robotia** [comment]
`at bspkrs.statuseffecthud.StatusEffectHUD.displayStatusEffects(StatusEffectHUD.java:217)`
The crash is caused by the bspkrs StatusEffectHUD mod.
